package noom.appModules;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import noom.pageObjects.AccountPage;
import noom.pageObjects.AddOnsPage;
import noom.pageObjects.AgeRangePage;
import noom.pageObjects.AntibioticPage;
import noom.pageObjects.BackIssuesPage;
import noom.pageObjects.BasicMetPage;
import noom.pageObjects.BuildPage;
import noom.pageObjects.BuildPlanPage;
import noom.pageObjects.ChoosePlanPage;
import noom.pageObjects.ConveniencePage;
import noom.pageObjects.CurrentHealthRiskPage;
import noom.pageObjects.DiabetesHistoryPage;
import noom.pageObjects.DietaryRestricitionsOrAllergiesPage;
import noom.pageObjects.EmailPage;
import noom.pageObjects.EnvironmentPage;
import noom.pageObjects.FirstGoalPage;
import noom.pageObjects.FocusInPlanPage;
import noom.pageObjects.FoodComboPage;
import noom.pageObjects.FoodFrequencyPage;
import noom.pageObjects.FourMonthPersonalizedCoursePage;
import noom.pageObjects.GenderPage;
import noom.pageObjects.HealthWeightPage;
import noom.pageObjects.HistoryPage;
import noom.pageObjects.HowBusyOnAnAverageDayPage;
import noom.pageObjects.HungryPage;
import noom.pageObjects.IdealWeightKgPage;
import noom.pageObjects.InfoDoctorsPage;
import noom.pageObjects.InfoPage;
import noom.pageObjects.InfoStudiesPage;
import noom.pageObjects.InfoTryPage;
import noom.pageObjects.LifeEventPage;
import noom.pageObjects.LifeStyleMetPage;
import noom.pageObjects.MyLifeStylePage;
import noom.pageObjects.OutsideMotivationPage;
import noom.pageObjects.PacePage;
import noom.pageObjects.PastExperiencePage;
import noom.pageObjects.PaymentPage;
import noom.pageObjects.PhysicalLimitationPage;
import noom.pageObjects.PrepareMealsPage;
import noom.pageObjects.SettingGoalsPage;
import noom.pageObjects.SocialPage;
import noom.pageObjects.WebEnrollmentPage;
import noom.pageObjects.WelcomePage;
import noom.pageObjects.WhereDidYouHearPage;
import noom.utility.Interaction;

public class GrowthBuyFlowAction {
	public static void execute(WebDriver driver) throws Exception {
		Interaction.clickUntilElementPresent(driver, HealthWeightPage.btn_LooseWeightForGood(), IdealWeightKgPage.xpath_idealWeightKg);
		IdealWeightKgPage.txtbx_idealWeightKg().sendKeys("85");
		IdealWeightKgPage.btn_surveyControlsNext().click();
		BasicMetPage.txtbx_basicHeightCm().sendKeys("185");
		BasicMetPage.txtbx_basicWeightKg().sendKeys("85");
		BasicMetPage.btn_surveyControlsNext().click();
		GenderPage.btn_questionOptionChecked().click();
		GenderPage.btn_surveyControlsNext().click();
		AgeRangePage.btn_questionOptionChecked().click();
		AgeRangePage.btn_surveyControlsNext().click();
		InfoPage.btn_surveyControlsNext().click();
		LifeStyleMetPage.btn_questionOptionChecked().click();
		LifeStyleMetPage.btn_surveyControlsNext().click();
		FoodComboPage.btn_questionOptionChecked().click();
		FoodComboPage.btn_surveyControlsNext().click();
		FoodFrequencyPage.btn_questionOptionChecked().click();
		FoodFrequencyPage.btn_surveyControlsNext().click();
		BuildPage.btn_surveyControlsNext().click();
		BackIssuesPage.btn_questionOptionChecked().click();
		BackIssuesPage.btn_surveyControlsNext().click();
		CurrentHealthRiskPage.btn_questionOptionChecked().click();
		CurrentHealthRiskPage.btn_surveyControlsNext().click();
		DiabetesHistoryPage.btn_questionOptionChecked().click();
		DiabetesHistoryPage.btn_surveyControlsNext().click();
		AntibioticPage.btn_questionOptionChecked().click();
		AntibioticPage.btn_surveyControlsNext().click();
		EnvironmentPage.btn_questionOptionChecked().click();
		Interaction.clickUntilElementPresent(driver, EnvironmentPage.btn_surveyControlsNext(), EmailPage.xpath_txtbxEmail);
		DateFormat dateFormat = new SimpleDateFormat("yyyyMMddHHmmss");
		Calendar cal = Calendar.getInstance();
		String time = dateFormat.format(cal.getTime());
		EmailPage.txtbx_email().sendKeys("auto" + time +"@ta.noom.com");
		Interaction.clickUntilElementPresent(driver, EmailPage.btn_surveyControlsNext(), "/html/body/div[1]/div/div/section[1]/div/div[2]/div/div/div[2]/div");
		Interaction.clickUntilElementPresent(driver, ChoosePlanPage.btn_claimMyPlan(), "//*[@class=\"survey__controls-next-btn\"]");
		Interaction.clickUntilElementPresent(driver, WelcomePage.btn_surveyControlsNext(), "//*[@id=\"root\"]/div/section/div[1]/div[2]/div[1]/div/label[3]");
		Interaction.clickUntilElementPresent(driver, WelcomePage.btn_surveyControlsNext(), "//*[@id=\"root\"]/div/section/div[1]/div[2]/div[1]/div/label[3]");
		Interaction.clickUntilElementPresent(driver, LifeEventPage.btn_questionOptionChecked(), "//*[@id=\"root\"]/div/section/div[1]/div[2]/div[2]/button[2]");
		LifeEventPage.btn_surveyControlsNext().click();
		HistoryPage.btn_questionOptionChecked().click();
		HistoryPage.btn_surveyControlsNext().click();
		PastExperiencePage.btn_questionOptionChecked().click();
		PastExperiencePage.btn_surveyControlsNext().click();
		MyLifeStylePage.btn_questionOptionChecked().click();
		MyLifeStylePage.btn_surveyControlsNext().click();
		SocialPage.btn_questionOptionChecked().click();
		SocialPage.btn_surveyControlsNext().click();
		OutsideMotivationPage.btn_questionOptionChecked().click();
		OutsideMotivationPage.btn_surveyControlsNext().click();
		ConveniencePage.btn_questionOptionChecked().click();
		ConveniencePage.btn_surveyControlsNext().click();
		FocusInPlanPage.btn_questionOptionChecked().click();
		FocusInPlanPage.btn_surveyControlsNext().click();
		PhysicalLimitationPage.btn_questionOptionChecked().click();
		PhysicalLimitationPage.btn_surveyControlsNext().click();
		DietaryRestricitionsOrAllergiesPage.btn_questionOptionChecked().click();
		DietaryRestricitionsOrAllergiesPage.btn_surveyControlsNext().click();
		InfoTryPage.btn_surveyControlsNext().click();
		HowBusyOnAnAverageDayPage.btn_questionOptionChecked().click();
		HowBusyOnAnAverageDayPage.btn_surveyControlsNext().click();
		PrepareMealsPage.btn_questionOptionChecked().click();
		PrepareMealsPage.btn_surveyControlsNext().click();
		HungryPage.btn_questionOptionChecked().click();
		HungryPage.btn_surveyControlsNext().click();
		InfoDoctorsPage.btn_surveyControlsNext().click();
		PacePage.btn_questionOptionChecked().click();
		PacePage.btn_surveyControlsNext().click();
		SettingGoalsPage.btn_surveyControlsNext().click();
		FirstGoalPage.btn_questionOptionChecked().click();
		FirstGoalPage.btn_surveyControlsNext().click();
		Interaction.clickUntilElementPresent(driver, InfoStudiesPage.btn_surveyControlsNext(), WhereDidYouHearPage.xpath_btn_questionOptionChecked);
		WhereDidYouHearPage.btn_questionOptionChecked().click();
		Interaction.clickUntilElementPresent(driver, WhereDidYouHearPage.btn_surveyControlsNext(), AccountPage.xpath_txtbx_name);
		AccountPage.txtbx_name().sendKeys("auto051719");
		Interaction.clickUntilElementPresent(driver, AccountPage.btn_surveyControlsNext(), BuildPlanPage.xpath_btn_no);
		Interaction.clickUntilElementPresent(driver, BuildPlanPage.btn_no(), BuildPlanPage.xpath_btn_no);
		Interaction.clickUntilElementPresent(driver, BuildPlanPage.btn_no(), BuildPlanPage.xpath_btn_seated);
		Interaction.clickUntilElementPresent(driver, BuildPlanPage.btn_seated(), FourMonthPersonalizedCoursePage.xpath_btn_continue);
		Actions action = new Actions(driver);
		action.moveToElement(FourMonthPersonalizedCoursePage.section_footer()).build().perform();;
		Interaction.clickUntilElementPresent(driver, FourMonthPersonalizedCoursePage.btn_continue(), PaymentPage.xpath_btn_save_profile);
		GrowthBuyFlowAction.paymentPageWorks(driver, action);
		AddOnsPage.chkbx_CustomMealWorkoutPlan().click();
		AddOnsPage.btn_Skip().click();
		WebDriverWait wait = new WebDriverWait(driver, 30000);
		wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(WebEnrollmentPage.xpath_txtbx_password)));
		WebEnrollmentPage.txtbx_password().sendKeys("pwosd1234");
		WebEnrollmentPage.txtbx_confirm_password().sendKeys("pwosd1234");
		WebEnrollmentPage.txtbx_phone_number().sendKeys("2015550123");
		WebEnrollmentPage.chkbx_male().click();
		WebEnrollmentPage.chkbx_imperial().click();
		WebEnrollmentPage.chkbx_kg().click();
		WebEnrollmentPage.txtbx_height_ft().sendKeys("5");
		WebEnrollmentPage.txtbx_height_in().sendKeys("5");
		WebEnrollmentPage.txtbx_weight_kg().sendKeys("65");
		WebEnrollmentPage.txtbx_id_age().sendKeys("35");
		WebEnrollmentPage.btn_finish_signup().click();
	}
	
	private static void paymentPageWorks(WebDriver driver, Actions action) {
		//TODO:: Needs refactoring and follow Page Object Model
		WebDriverWait wait = new WebDriverWait(driver, 30000);
		wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("braintree-hosted-field-number")));
		driver.switchTo().frame(driver.findElement(By.id("braintree-hosted-field-number")));
		driver.findElement(By.name("credit-card-number")).sendKeys("4111111111111111");
		driver.switchTo().defaultContent();
		driver.switchTo().frame(driver.findElement(By.id("braintree-hosted-field-expirationDate")));
		driver.findElement(By.name("expiration")).sendKeys("1020");
		driver.switchTo().defaultContent();
		driver.switchTo().frame(driver.findElement(By.id("braintree-hosted-field-cvv")));
		driver.findElement(By.name("cvv")).sendKeys("123");
		driver.switchTo().defaultContent();
		action.moveToElement(PaymentPage.section_footer()).build().perform();
		driver.findElement(By.xpath("//button[contains(text(), 'Save Profile')]")).click();
		System.out.println("looking for gurantee title");
		wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//p[@class='guarantee-title']")));
	}
}
