/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package noom;

import noom.appModules.GrowthBuyFlowAction;
import noom.pageObjects.BaseClass;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class AppTest {
	public static WebDriver driver;

	@Before
	public void initialize() {
		System.setProperty("webdriver.chrome.driver", "/Users/prince/Downloads/chromedriver");
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		new BaseClass(driver);
	}

    @Test
	public void testBuyFlow() throws Exception {
		driver.get("https://growthstaging.noom.com/programs/health-weight/rfqa/");
		GrowthBuyFlowAction.execute(driver);
		assert(true);
    }

	@After
	public void closeDriver() {
//		driver.close();
	}
}